Adds Unity Explorer Plus
hk-modding/modlinks pull request #162
Opened 2022-02-11 13:28 UTC by HKLab

2022-02-11 18:12 UTC, TheMulhima commented
What is the difference between this and UnityExplorer?

2022-02-11 18:41 UTC, SFGrenade requested changes

2022-02-11 18:41 UTC, SFGrenade commented on ModLinks.xml
> +			<Dependency>Unity Explore</Dependency>
missing letter

2022-02-12 04:21 UTC, HKLab commented
> What is the difference between this and UnityExplorer?
Extended the functionality of the Mouse Inspector
[README](https://github.com/HKLab/UnityExplorerPlus/blob/main/README.md)

2022-02-12 13:59 UTC, merged